controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

logout:
    path: /logout
    controller: App\Controller\PublicController::logout

reservation:
    path: /reservation
    controller: App\Controller\HouseController::reservation
